routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->to(route('photo.index'));
});

Route::resource('/photo', 'SimplePhotoController', ['parameters' => [
    'photo' => 'simplePhoto'
]]);

app/Models/SimplePhoto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SimplePhoto extends Model
{
    use SoftDeletes;

    protected $casts = [
        'properties' => 'object'
    ];

    protected $fillable = [
        'name',
        'filename',
        'properties',
        'status',
    ];

    public function getUrlAttribute()
    {
        return \Storage::disk('media')->url(config('spu.path') . \DIRECTORY_SEPARATOR . $this->id . \DIRECTORY_SEPARATOR . config('spu.converted_path') . \DIRECTORY_SEPARATOR . $this->filename);
    }

    public function getUrlOriginalAttribute()
    {
        return \Storage::disk('media')->url(config('spu.path') . \DIRECTORY_SEPARATOR . $this->id . \DIRECTORY_SEPARATOR . $this->filename);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SimplePhotoController.php
<?php

namespace App\Http\Controllers;

use App\Models\SimplePhoto;
use App\Http\Requests\SimplePhotoRequest;

class SimplePhotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $photos = SimplePhoto::all();
        return \view('index', ['photos' => $photos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\SimplePhotoRequest  $request
     * 
     * @return \Illuminate\Http\Response
     */
    public function store(SimplePhotoRequest $request)
    {
        $newPhotoId = \SPT::storePhoto($request);

        return \redirect(route('photo.show', $newPhotoId));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\SimplePhoto  $simplePhoto
     * 
     * @return \Illuminate\Http\Response
     */
    public function show(SimplePhoto $simplePhoto)
    {
        return \view('show', ['photo' => $simplePhoto]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\SimplePhoto  $simplePhoto
     * 
     * @return \Illuminate\Http\Response
     */
    public function edit(SimplePhoto $simplePhoto)
    {
        return \view('edit', ['photo' => $simplePhoto]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\SimplePhotoRequest  $request
     * @param  \App\Models\SimplePhoto  $simplePhoto
     * 
     * @return \Illuminate\Http\Response
     */
    public function update(SimplePhotoRequest $request, SimplePhoto $simplePhoto)
    {
        $simplePhotoId = \SPT::storePhoto($request, $simplePhoto);

        return \redirect(route('photo.show', $simplePhotoId));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\SimplePhoto  $simplePhoto
     * 
     * @return \Illuminate\Http\Response
     */
    public function destroy(SimplePhoto $simplePhoto)
    {
        $simplePhoto->delete();
        return response()->json('OK', 200);
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('APP_NAME', 'Simple Photo') }}</title>
        <link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}" />
        @stack('styles')
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
    <script src="{{ asset('js/app.js') }}"></script>
    @stack('additional-js')
    <script>
        @stack('scripts')
    </script>
</html>

resources/views/create.blade.php
@extends('app')

@section('content')
<div class="centerFlex">
    <div class="centered">
        <div class="row">
            <div class="col-md-6">
                <form method="post" action="{{ route('photo.store') }}" enctype="multipart/form-data" id="upload_form">
                    @csrf
                    <div class="form-group">
                        <label for="name">Nazwa</label>
                        <input class="form-control" type="text" name="name" id="name" value={{ old('name') }}>
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="image" name="image">
                        <label class="custom-file-label text-left" for="image">Wybierz plik z dysku</label>
                        <span class="text-danger">{{ $errors->first('image') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="fit" id="nochange" value="auto" @if(old('fit')=='auto' || empty(old('properties'))) checked @endif>
                            <label class="form-check-label" for="nochange">no change</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="fit" id="contain" value="contain" @if(old('fit')=='contain' ) checked @endif>
                            <label class="form-check-label" for="contain">contain</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="fit" id="cover" value="cover" @if(old('fit')=='cover' ) checked @endif>
                            <label class="form-check-label" for="cover">cover</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="fit" id="scale" value="scale" @if(old('fit')=='scale' ) checked @endif>
                            <label class="form-check-label" for="scale">scale</label>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <input class="btn btn-primary" type="submit" value="Wyślij">
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <div id="image_preview">
                    <p>PREVIEW</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('additional-js')
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
@endpush
@push('scripts')
$(document).ready(function () {
bsCustomFileInput.init()

$('#image').change(function(){
let reader = new FileReader();
reader.onload = (e) => {
$('#image_preview').css('background-image', "url("+ e.target.result + ")");
}
reader.readAsDataURL(this.files[0]);
});

$("input[type='radio']").change(function(){
if (this.value == 'scale') {
$('#image_preview').css('background-size', "300px 300px");
} else {
$('#image_preview').css('background-size', this.value).css('background-position', 'center');
}
});
})
@endpush

resources/views/edit.blade.php
@extends('app')

@section('content')
<div class="centerFlex">
    <div class="centered">
        <div class="row">
            <div class="col-md-6">
                <form method="post" action="{{ route('photo.update', $photo->id) }}" enctype="multipart/form-data" id="upload_form">
                    @method('put')
                    @csrf
                    <div class="form-group">
                        <label for="name">Nazwa</label>
                        <input class="form-control" type="text" name="name" id="name" value={{ $photo->name }}>
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="image" name="image">
                        <label class="custom-file-label text-left" for="image">{{ trim($photo->filename) }}</label>
                        <span class="text-danger">{{ $errors->first('image') }}</span>
                    </div>
                    <div class="form-group mt-3">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="fit" id="nochange" value="auto" @if($photo->properties->fit=='auto' || empty($photo->properties->fit)) checked @endif>
                            <label class="form-check-label" for="nochange">no change</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="fit" id="contain" value="contain" @if($photo->properties->fit=='contain') checked @endif>
                            <label class="form-check-label" for="contain">contain</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="fit" id="cover" value="cover" @if($photo->properties->fit=='cover') checked @endif>
                            <label class="form-check-label" for="cover">cover</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="fit" id="scale" value="scale" @if($photo->properties->fit=='scale') checked @endif>
                            <label class="form-check-label" for="scale">scale</label>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <div id="image_preview">
                    <p>PREVIEW</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('additional-js')
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
@endpush
@push('scripts')
$(document).ready(function () {
bsCustomFileInput.init()

$('#image_preview').css('background-image', "url({{ $photo->url_original }}?ver={{ time() }})");
$('#image_preview').css('background-size', "{{ $photo->properties->fit == 'scale' ? '300px 300px' : $photo->properties->fit }}");
$('#image_preview').css('background-position', "{{ $photo->properties->fit == 'auto' ? 'initial' : 'center' }}");

$('#image').change(function(){
let reader = new FileReader();
reader.onload = (e) => {
$('#image_preview').css('background-image', "url("+ e.target.result + ")");
}
reader.readAsDataURL(this.files[0]);
});

$("input[type='radio']").change(function(){
if (this.value == 'scale') {
$('#image_preview').css('background-size', "300px 300px");
} else if (this.value == 'auto') {
    $('#image_preview').css('background-size', this.value).css('background-position', 'initial');
} else {
$('#image_preview').css('background-size', this.value).css('background-position', 'center');
}
});
})
@endpush

resources/views/index.blade.php
@extends('app')

@section('content')
    <div class="row">
        <a href="{{ route('photo.create') }}" class="btn btn-primary">Dodaj nowy</a>
    </div>
    <div class="row">
        @foreach ($photos as $photo)
        <a href="{{ route('photo.show', $photo->id) }}" title="{{ $photo->name }}">
            <div class="image-list-item" style="background-image: url({{ $photo->url }}?ver={{ time() }});"></div>
        </a>
        @endforeach
    </div>
@endsection

resources/views/show.blade.php
@extends('app')

@section('content')
<div class="centerFlex">
    <div class="centered">
        <h4>{{ $photo->name }}</h4>
        <img src="{{ $photo->url }}?ver={{ time() }}" />
        <br /><br />
        <a href="{{ route('photo.create') }}" class="btn btn-primary">Dodaj</a>
        <a href="{{ route('photo.edit', $photo->id) }}" class="btn btn-primary">Edytuj</a>
        <a href="{{ route('photo.index') }}" class="btn btn-primary">Lista</a>
        <a href="{{ route('photo.destroy', $photo->id) }}" class="btn btn-danger" id="photo_delete">Usuń</a>
    </div>
</div>
@endsection

@push('scripts')
$(document).ready( function () {
    $('#photo_delete').click(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var delete_url = $(this).attr("href");
        if (confirm('Na pewno usunąć?!')) {
            $.ajax({
                type: "POST",
                dataType: "JSON",
                url: delete_url,
                data: {_method: "DELETE"},
                success: function() {
                    if (confirm('Obraz został usunięty!')) {
                        window.location.replace("{{ route('photo.index') }}");
                    }
                },
                error: function(a,b,c) {
                    alert(c);
                }
            });
        }
    })
});
@endpush